# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170212_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='latitude',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='lists',
            name='longitude',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
