# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20170213_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='longitude',
        ),
        migrations.AddField(
            model_name='lists',
            name='category',
            field=models.CharField(default='other', max_length=30),
        ),
    ]
