# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20170214_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
