# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20170214_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.CharField(default=19.1239, max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.CharField(default=72.8361, max_length=20),
        ),
    ]
