# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_remove_notification_list_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='latitude',
            new_name='store_latitude',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='longitude',
            new_name='store_longitude',
        ),
    ]
