# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20170214_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='store_latitude',
            field=models.CharField(default=19.1239, max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='store_longitude',
            field=models.CharField(default=72.8361, max_length=20),
        ),
    ]
