# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20170331_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lists',
            old_name='task',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='lists',
            old_name='category',
            new_name='recipient',
        ),
    ]
